---
- hosts: all
  vars_files:
  - vars.yml

  gather_facts: false

  pre_tasks:

  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-dev)"
    register: output
    changed_when:
    - output.stdout != ""
    - output.stdout != "\r\n"

  - name: Gather facts
    setup:

  tasks:

  - name: Install system packages
    apt: pkg={{ item }} update-cache=yes
    with_items: "{{ system_packages }}"

  - name: Create directory for app
    file:
      path: "{{ install_root }}"
      state: directory
      group: deploy
      mode: u=rwx,g=rwx,o=rx,g+s

  - name: Create directory for www files
    file:
      path: "{{ www_root }}"
      state: directory
      group: www-data
      mode: u=rwx,g=rwx,o=rx,g+s

  - name: Make uwsgi apps-enabled writable by deploy group
    file:
      path: /etc/uwsgi/apps-enabled
      state: directory
      group: deploy
      mode: u=rwx,g=rwx,o=rx

  - name: Make nginx sites-enabled writable by deploy group
    file:
      path: /etc/nginx/sites-enabled
      state: directory
      group: deploy
      mode: u=rwx,g=rwx,o=rx

  - name: Remove default nginx site
    file: path=/etc/nginx/sites-enabled/default state=absent

  - name: Create letsencrypt keys directory
    file: path="{{ letsencrypt_keys }}" state=directory

  - name: Create letsencrypt certs directory
    file: path="{{ letsencrypt_certs }}" state=directory

  - name: Create letsencrypt challenges directory
    file:
      path: "{{ letsencrypt_challenges }}"
      state: directory
      group: www-data
      mode: u=rwx,g=rwx,o=rx,g+s

  - name: Generate letsencrypt account private key
    command:
      "openssl genrsa -out {{ letsencrypt_account_key }} {{ rsa_key_size }}"
    args:
      creates: "{{ letsencrypt_account_key }}"

  - name: Make letsencrypt account private key readable by root only
    file:
      path: "{{ letsencrypt_account_key }}"
      mode: u=rw,g=,o=

  - name: Generate HTTPS private key
    command: "openssl genrsa -out {{ https_key }} {{ rsa_key_size }}"
    args:
      creates: "{{ https_key }}"

  - name: Make HTTPS private key readable by root only
    file:
      path: "{{ https_key }}"
      mode: u=rw,g=,o=

  - name: Generate certificate signing request
    command: "openssl req -new
      -key {{ https_key }}
      -out {{ https_csr }}
      -nodes -subj '/C=US/ST=NC/L=CH/O=UNC/CN={{ server_name }}'"
    args:
      creates: "{{ https_csr }}"

  - name: Make certificate signing request readable by root only
    file:
      path: "{{ https_csr }}"
      mode: u=rw,g=,o=

  - name: Request letsencrypt challenge
    letsencrypt:
      acme_directory: "{{ letsencrypt_acme_directory }}"
      account_email: "{{ letsencrypt_account_email }}"
      account_key: "{{ letsencrypt_account_key }}"
      csr: "{{ https_csr }}"
      dest: "{{ https_cert }}"
      remaining_days: 30
    register: challenge

  - name: Create challenge directory
    file:
      path: "{{ letsencrypt_challenges }}/{{ challenge_dest | dirname }}"
      state: directory
    when: challenge is changed
    vars:
      challenge_dest:
        "{{ challenge['challenge_data'][server_name]['http-01']['resource'] }}"

  - name: Move challenge to publicly served directory
    copy:
      dest: "{{ letsencrypt_challenges }}/{{ challenge_file['resource'] }}"
      content: "{{ challenge_file['resource_value'] }}"
      mode: u=rw,g=r,o=r
    when: challenge is changed
    vars:
      challenge_file:
        "{{ challenge['challenge_data'][server_name]['http-01'] }}"

  - name: Copy nginx config to serve challenge
    template:
      src: files/nginx-challenge.conf.j2
      dest: "/etc/nginx/sites-enabled/{{ server_name }}-challenge.conf"
      group: deploy
    when: challenge is changed
    vars:
      challenge_dest:
        "{{ challenge['challenge_data'][server_name]['http-01']['resource'] }}"
    notify:
    - Restart nginx

  # ensure that nginx gets restarted after enabling challenge site
  - meta: flush_handlers

  - name: Respond to challenge and fetch certificate
    letsencrypt:
      acme_directory: "{{ letsencrypt_acme_directory }}"
      account_email: "{{ letsencrypt_account_email }}"
      account_key: "{{ letsencrypt_account_key }}"
      csr: "{{ https_csr }}"
      dest: "{{ https_cert }}"
      data: "{{ challenge }}"
      remaining_days: 30

  - name: Remove nginx site for challenge
    file:
      path: "/etc/nginx/sites-enabled/{{ server_name }}-challenge.conf"
      state: absent
    notify:
    - Restart nginx

  - name: Download intermediate cerificates
    get_url:
      url: "https://letsencrypt.org/certs/{{ item }}"
      dest: "{{ letsencrypt_certs }}/{{ item }}"
      mode: 0444
    with_items:
    - lets-encrypt-x3-cross-signed.pem
    - lets-encrypt-x4-cross-signed.pem

  - name: Create a full-chain certificate from components
    shell: >
      cat {{ https_cert }}
      {{ letsencrypt_certs }}/lets-encrypt-x3-cross-signed.pem
      {{ letsencrypt_certs }}/lets-encrypt-x4-cross-signed.pem
      > {{ https_chain }}
    when: challenge is changed

  - name: Create Diffie–Hellman parameters
    shell: >
      openssl dhparam -dsaparam -out {{ https_dhparams }} {{ rsa_key_size }}
    when: challenge is changed

  - name: Clone/pull project repo
    git:
      repo: "{{ project_repo }}"
      dest: "{{ install_root }}"
    notify:
    - Restart uwsgi app service

  - name: Install python packages
    pip:
      requirements: "{{ install_root }}/requirements.txt"
      virtualenv: "{{ install_root }}/venv"
      virtualenv_command: /usr/bin/python3 -m venv
    notify:
    - Restart uwsgi app service

  - name: Copy secrets file
    copy:
      src: files/secrets.py
      dest: "{{ install_root }}/{{ project_name }}/secrets.py"
      group: deploy

  - name: Update database schema
    django_manage:
      command: migrate
      app_path: "{{ install_root }}"
      virtualenv: "{{ install_root }}/venv"

  - name: Collect static files
    django_manage:
      command: collectstatic
      app_path: "{{ install_root }}"
      virtualenv: "{{ install_root }}/venv"

  - name: Install uwsgi app socket
    template:
      src: templates/uwsgi-app.socket.j2
      dest: "/etc/systemd/system/{{ server_name }}.socket"
    register: installed_socket
    notify:
    - Restart uwsgi app socket
    - Restart uwsgi app service

  - name: Install uwsgi app service
    template:
      src: templates/uwsgi-app.service.j2
      dest: "/etc/systemd/system/{{ server_name }}.service"
    register: installed_service
    notify:
    - Restart uwsgi app service

  - name: Tell systemd to reload configs
    systemd: daemon_reload=yes
    when: installed_socket is changed or installed_service is changed

  - name: Copy uwsgi config
    template:
      src: templates/uwsgi.ini.j2
      dest: "{{ uwsgi_conf_dir }}{{ server_name }}.ini"
      owner: www-data
      group: www-data
    notify:
    - Restart uwsgi app service

  - name: Copy nginx config
    template:
      src: templates/nginx.conf.j2
      dest: "{{ nginx_conf_dir }}{{ server_name }}.conf"
    notify:
    - Restart nginx

  - name: Ensure uwsgi app socket is running
    systemd:
      name: "{{ server_name }}.socket"
      enabled: yes
      state: started

  - name: Ensure uwsgi app service is enabled
    systemd:
      name: "{{ server_name }}.service"
      enabled: yes

  - name: Ensure nginx is running
    systemd:
      name: nginx.service
      enabled: yes
      state: started

  handlers:

  - name: Restart nginx
    systemd:
      name: nginx.service
      state: restarted

  - name: Restart uwsgi app socket
    systemd:
      name: "{{ server_name }}.socket"
      state: restarted

  - name: Restart uwsgi app service
    systemd:
      name: "{{ server_name }}.service"
      state: stopped # it will start again on demand
