---
- name: Create directory for WWW files
  file:
    path: "{{ www_root }}"
    state: directory
    owner: www-data

- name: Fetch site tarball
  get_url:
    url: "{{ project_repo }}/archive/site.tar.gz"
    dest: /tmp/unc-ch-aaup-site.conf

- name: Extract site
  unarchive:
    remote_src: yes
    src: /tmp/unc-ch-aaup-site.conf
    dest: "{{ www_root }}"
    extra_opts:
    - --strip-components=1

- name: Remove tarball
  file:
    path: /tmp/unc-ch-aaup-site.conf
    state: absent

- name: Copy nginx config
  template:
    src: templates/nginx.conf.j2
    dest: "{{ nginx_conf_dir }}{{ server_name }}.conf"
  notify:
  - Restart nginx

- name: Ensure nginx is running
  systemd:
    name: nginx.service
    enabled: yes
    state: started



